/* soapARLiveBroadcastBindingProxy.h
   Generated by gSOAP 2.8.3 from ARGoldSoap.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapARLiveBroadcastBindingProxy_H
#define soapARLiveBroadcastBindingProxy_H
#include "soapH.h"

class SOAP_CMAC ARLiveBroadcastBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'ARLiveBroadcastBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	ARLiveBroadcastBindingProxy();
	/// Constructor with copy of another engine state
	ARLiveBroadcastBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	ARLiveBroadcastBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	ARLiveBroadcastBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ARLiveBroadcastBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ARLiveBroadcastBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ARLiveBroadcastBindingProxy();
	/// Initializer used by constructors
	virtual	void ARLiveBroadcastBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'ARLiveBroadcast' (returns error code or SOAP_OK)
	virtual	int ARLiveBroadcast(std::string GSName, std::string GameName, std::string Type, std::string Data, std::string &return_) { return ARLiveBroadcast(NULL, NULL, GSName, GameName, Type, Data, return_); }
	virtual	int ARLiveBroadcast(const char *endpoint, const char *soap_action, std::string GSName, std::string GameName, std::string Type, std::string Data, std::string &return_);
};
#endif
